clmpkg/objects/Agreement_Revision_History__c.object
<CustomObject>
    <description>This object holds the changes made on agreements during amendment.This drives the data on Summary Component.</description>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipName>Agreement_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Channel_SF_ID__c</fullName>
        <label>Channel SF ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agreement</fullName>
                </value>
                <value>
                    <fullName>Agreement Channel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement Revision History</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Agreement Revision Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Revision Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

clmpkg/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

clmpkg/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Agreement__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

clmpkg/classes/PNR_AgreementRevHistorySelector_Test.cls
/*
 * Test class for PNR_AgreementRevHistorySelector 
*/
@isTest
private class PNR_AgreementRevHistorySelector_Test {

    private final static Integer NUM_DEFAULT_STREAMERS = 1;

    @testSetup
    private static void setupData() {
        List<Account> accounts = PNR_TestDataFactory.createStreamers(NUM_DEFAULT_STREAMERS);
        Set<Id> accountIds = new Map<Id, Account>(accounts).keySet();       
               
        PNR_TestDataFactory.createPartnerContentAcquisitionOpportunities(accountIds, 1);
        List<Opportunity> opptys = [SELECT Id FROM Opportunity];
        List<Id> opIds=new List<Id>();
        for(Opportunity op:opptys){
            opIds.add(op.Id);
        }
        
        List<Apttus__APTS_Agreement__c> agg=PNR_TestDataFactory.insertTwitchContentLicenseAgrmnts(opIds,1);
        insert agg;       
       
        List<Agreement_Revision_History__c> agrev=PNR_TestDataFactory.insertAgreementRevisions(agg[0].Id,1);
        insert agrev;
    }

    @isTest
    private static void test_selectById() {
        Set<Id> agIds =new Set<Id>();
        Set<Id> chIds=new Set<Id> () ;
        List<Agreement_Revision_History__c> agrs = [SELECT Id,Channel_SF_ID__c, Agreement__c, Type__c, To__c FROM Agreement_Revision_History__c];
       
        for(Agreement_Revision_History__c arh:agrs){
            if(arh.Type__c=='Agreement'){             
               agIds.add(Id.valueof(arh.Agreement__c));
            }
            else if(arh.Type__c=='Agreement Channel'){                
                 agIds.add(Id.valueof(arh.Agreement__c));
                 chIds.add(Id.valueof(arh.Channel_SF_ID__c));
            }           
        }
        
        List<Agreement_Revision_History__c> agr = [SELECT Id,Channel_SF_ID__c, Agreement__c, Type__c FROM Agreement_Revision_History__c where Type__c='Agreement' ];
        List<Agreement_Revision_History__c> agrchnl = [SELECT Id,Channel_SF_ID__c, Agreement__c, Type__c FROM Agreement_Revision_History__c where Type__c='Agreement Channel'];
        List<Agreement_Revision_History__c> agrchnlr = [SELECT Id,Channel_SF_ID__c, Agreement__c, Type__c FROM Agreement_Revision_History__c where Type__c='Agreement Channel' and Channel_SF_ID__c IN:chIds ];
        
        
        System.assertEquals(agr.size(), new PNR_AgreementRevHistorySelector().selectAgreementRevision(agIds).size());
        System.assertEquals(agrchnl.size(), new PNR_AgreementRevHistorySelector().selectAgrmntChnlRev(agIds).size());
        System.assertEquals(agrchnlr.size(), new PNR_AgreementRevHistorySelector().selectByAgrmntChnl(agIds,chIds).size());
        
    }

    
}