clmpkg/objects/AgreementChannel__c.object
<CustomObject>
    <description>Object is used for Content License agreements, which can have one-to-many channels associated to it.</description>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Channels</relationshipLabel>
        <relationshipName>Agreement_Channels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ChannelID__c</fullName>
        <label>Channel ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ChannelName__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Channel Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Agreement Channels</relationshipLabel>
        <relationshipName>Agreement_Channels</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EffectiveDateFrom__c</fullName>
        <label>Effective Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EffectiveDateTerm__c</fullName>
        <formula>IF(NOT(ISNULL(EffectiveDateTo__c)), 
TEXT(MONTH(EffectiveDateFrom__c))+&quot;/&quot; +TEXT(DAY(EffectiveDateFrom__c))+&quot;/&quot; +TEXT(YEAR(EffectiveDateFrom__c)) &amp; &quot; - &quot; &amp; TEXT(MONTH(EffectiveDateTo__c))+&quot;/&quot; +TEXT(DAY(EffectiveDateTo__c))+&quot;/&quot; +TEXT(YEAR(EffectiveDateTo__c)), 

IF(NOT(ISNULL(EffectiveDateFrom__c)), 
TEXT(MONTH(EffectiveDateFrom__c))+&quot;/&quot; +TEXT(DAY(EffectiveDateFrom__c))+&quot;/&quot; +TEXT(YEAR(EffectiveDateFrom__c)), 

&apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Effective Date/Term</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EffectiveDateTo__c</fullName>
        <label>Effective End Date</label>
        <type>Date</type>
    </fields>
    <label>Agreement Channel</label>
    <nameField>
        <displayFormat>AC-{00000}</displayFormat>
        <label>Agreement Channel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Channels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

clmpkg/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

clmpkg/classes/PNR_AgreementChannelSelector.cls
public with sharing class PNR_AgreementChannelSelector extends PNR_SObjectSelector {

    public PNR_AgreementChannelSelector() {
        this(false);
    }

    public PNR_AgreementChannelSelector(Boolean includeFieldSetFields) {
        this(includeFieldSetFields, true, false);
    }

    public PNR_AgreementChannelSelector(Boolean includeFieldSetFields, Boolean enforceCRUD, Boolean enforceFLS) {
        super(includeFieldSetFields, enforceCRUD, enforceFLS);
    }
      
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            AgreementChannel__c.Id,
            AgreementChannel__c.Name,
            AgreementChannel__c.Agreement__c,
            AgreementChannel__c.ChannelID__c,
            AgreementChannel__c.ChannelName__c,
            AgreementChannel__c.EffectiveDateTerm__c,
            AgreementChannel__c.EffectiveDateFrom__c,
            AgreementChannel__c.EffectiveDateTo__c
           
        };
    }
    
    public Schema.SObjectType getSObjectType() {
        return AgreementChannel__c.sObjectType;
    }
    
    public List<AgreementChannel__c> selectByAgreementId(Set<Id> agId,Set<Id> channelId) {
        assertIsAccessible();
        PNR_AgreementSelector agreementSelector = new PNR_AgreementSelector();
        String agreementquery=agreementSelector.selectByAggId('Agreement__r');
        
        String query = String.format(
                ' SELECT {0}' + ','+'{2}'+
                        ' FROM {1}' +
                        ' WHERE Agreement__c =: agId'+
                        ' AND ID=: channelId',                   
                new List<String> {
                        getFieldListString(),
                        getSObjectName(),
                        agreementquery
                     
                }
        );
        system.debug('channel query' +query);
        return Database.query(query);
    }
}