clmpkg/objects/Agreement_Revision_History__c.object
<CustomObject>
    <description>This object holds the changes made on agreements during amendment.This drives the data on Summary Component.</description>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipName>Agreement_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Channel_SF_ID__c</fullName>
        <label>Channel SF ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FieldAPI__c</fullName>
        <label>Field API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldLabel__c</fullName>
        <label>Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agreement</fullName>
                </value>
                <value>
                    <fullName>Agreement Channel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement Revision History</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Agreement Revision Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Revision Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

clmpkg/classes/PNR_AgreementRevHistorySelector.cls
public with sharing class PNR_AgreementRevHistorySelector extends PNR_SObjectSelector {

    public PNR_AgreementRevHistorySelector() {
        this(false);
    }

    public PNR_AgreementRevHistorySelector(Boolean includeFieldSetFields) {
        this(includeFieldSetFields, true, false);
    }

    public PNR_AgreementRevHistorySelector(Boolean includeFieldSetFields, Boolean enforceCRUD, Boolean enforceFLS) {
        super(includeFieldSetFields, enforceCRUD, enforceFLS);
    }
    
    
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Agreement_Revision_History__c.Id,
            Agreement_Revision_History__c.FieldAPI__c,
            Agreement_Revision_History__c.FieldLabel__c,
            Agreement_Revision_History__c.From__c,
            Agreement_Revision_History__c.To__c,
            Agreement_Revision_History__c.Channel_SF_ID__c
          
          
        };
    }
    
    public Schema.SObjectType getSObjectType() {
        return Agreement_Revision_History__c.sObjectType;
    }
    
    public List<Agreement_Revision_History__c> selectAgreementRevision(Set<Id> agId) {
        assertIsAccessible();
        
        String agreement='Agreement';
        
        String query = String.format(
                ' SELECT {0}' +
                        ' FROM {1}' +
                        ' WHERE Agreement__c =: agId'+
                        ' AND Type__c=:agreement',
                                    
                new List<String> {
                        getFieldListString(),
                        getSObjectName()  
                }
        );
        
        system.debug('agreement query' +query);
        return Database.query(query);
        
    }
    
    public List<Agreement_Revision_History__c> selectAgrmntChnlRev(Set<Id> agId) {
        assertIsAccessible();
        
        String channel='Agreement Channel';
        
        String query = String.format(
                ' SELECT {0}' +
                        ' FROM {1}' +
                        ' WHERE Agreement__c =: agId'+
                        ' AND Type__c=: channel',
                                      
                new List<String> {
                        getFieldListString(),
                        getSObjectName()
                                            
                }
        );
        
        system.debug('agreement channel query' +query);
        return Database.query(query);
        
    }
    
    public List<Agreement_Revision_History__c> selectByAgrmntChnl(Set<Id> agId,Set<Id> channelId) {
        assertIsAccessible();
          
        String channel='Agreement Channel';
        
        String query = String.format(
                ' SELECT {0}' +
                        ' FROM {1}' +
                        ' WHERE Agreement__c =: agId'+
                        ' AND Type__c=: channel'+
                        ' AND Channel_SF_ID__c=: channelId',               
                new List<String> {
                        getFieldListString(),
                        getSObjectName()
                                           
                }
        );
        
        system.debug('channel query' +query);
        return Database.query(query);
        
    }

}