clmpkg/objects/Agreement_Revision_History__c.object
<CustomObject>
    <description>This object holds the changes made on agreements during amendment.This drives the data on Summary Component.</description>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipName>Agreement_Histories</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Channel_Action__c</fullName>
        <label>Channel Action</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Create</fullName>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Channel_SF_ID__c</fullName>
        <label>Channel SF ID</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>FieldAPI__c</fullName>
        <label>Field API</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldLabel__c</fullName>
        <label>Field Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>From__c</fullName>
        <label>From</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To__c</fullName>
        <label>To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Agreement</fullName>
                </value>
                <value>
                    <fullName>Agreement Channel</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement Revision History</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>Agreement Revision Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Revision Histories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

clmpkg/objects/AgreementChannel__c.object
<CustomObject>
    <description>Object is used for Content License agreements, which can have one-to-many channels associated to it.</description>
    <fields>
        <fullName>Agreement__c</fullName>
        <label>Agreement</label>
        <referenceTo>Apttus__APTS_Agreement__c</referenceTo>
        <relationshipLabel>Agreement Channels</relationshipLabel>
        <relationshipName>Agreement_Channels</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Agreement Channel</label>
    <nameField>
        <displayFormat>AC-{00000}</displayFormat>
        <label>Agreement Channel Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agreement Channels</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

clmpkg/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_Start_Date__c</fullName>
        <description>The effective date of the agreement</description>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N50000001Xl0FEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Term_Months__c</fullName>
        <description>Indicates the duration in months of the contract from the start date</description>
        <label>Term (Months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

clmpkg/classes/PNR_AgreementService.cls
public with sharing class PNR_AgreementService {
    

    public static void createAgreementRevisions(List<Apttus__APTS_Agreement__c> agList) {      
        List<Agreement_Revision_History__c> revisionInsertList=new List<Agreement_Revision_History__c>();
        Schema.FieldSet fieldSetObj = Schema.SObjectType.Apttus__APTS_Agreement__c.fieldSets.Agreement_Revisions_History;
        
        for(Apttus__APTS_Agreement__c agreement:agList){
            for(Schema.FieldSetMember fsMember:fieldSetObj.getFields()){
                Agreement_Revision_History__c revisionTo=new Agreement_Revision_History__c();
                revisionTo.Agreement__c=agreement.Id;
                revisionTo.FieldLabel__c=fsMember.getLabel();
                revisionTo.FieldAPI__c=fsMember.getFieldPath();              
                revisionTo.From__c=String.valueof(agreement.get(fsMember.getFieldPath()));
                revisionTo.Type__c='Agreement';

                revisionInsertList.add(revisionTo);

            }
        }
        system.debug('revisionInsertList:::'+revisionInsertList.size());
        insert revisionInsertList;
    }

    
    public static void createChannelRevisions(Set<Id> agreementIds,Set<Id> channelIds){
        List<AgreementChannel__c> channelList=new List<AgreementChannel__c>();
        channelList=new PNR_AgreementChannelSelector().selectByAgreementId(agreementIds,channelIds);
        List<Agreement_Revision_History__c> revisionChannelInsertList=new List<Agreement_Revision_History__c>();
        
        system.debug('channelList-create method:::'+channelList.size());

        Schema.FieldSet fieldSetObj = Schema.SObjectType.AgreementChannel__c.fieldSets.Channel_Revision_History;
        for(AgreementChannel__c channel:channelList){
            for(Schema.FieldSetMember fsMember:fieldSetObj.getFields()){
                Agreement_Revision_History__c channelRevisionTo=new Agreement_Revision_History__c();
                    if(channel.Agreement__r.Apttus__Status__c=='In Amendment' && channel.Agreement__r.Apttus__Status_Category__c=='Request'){
                        channelRevisionTo.Agreement__c=channel.Agreement__c;
                        channelRevisionTo.FieldLabel__c=fsMember.getLabel();
                        channelRevisionTo.FieldAPI__c=fsMember.getFieldPath();
                        
                        channelRevisionTo.From__c=String.valueof(channel.get(fsMember.getFieldPath()));
                        channelRevisionTo.Type__c='Agreement Channel';
                        channelRevisionTo.Channel_Action__c='Create';
                        channelRevisionTo.Channel_SF_ID__c=channel.ID;

                        revisionChannelInsertList.add(channelRevisionTo);
                    }
            }
        }

        system.debug('revisionChannelInsertList:::'+revisionChannelInsertList.size());
        insert revisionChannelInsertList;

    }

    //Update Agreement Channel to Revision Histroy
    @TestVisible
    public static void updateAgreementChannelRevisions(Set<Id> agreementIds,Set<Id> channelIds,Map<Id,String> channelMap) { 
       List<Agreement_Revision_History__c> revisionChannelUpdateListFinal=new List<Agreement_Revision_History__c>();
       
       List<AgreementChannel__c> channelList=new List<AgreementChannel__c>();
       channelList=new PNR_AgreementChannelSelector().selectByAgreementId(agreementIds,channelIds);
        
       List<Agreement_Revision_History__c> revisionChannelUpdateList= new PNR_AgreementRevHistorySelector(). selectAgrmntChnlRev(agreementIds);
       system.debug('%%%revisionChannelUpdateListNEW - Update method%%%'+revisionChannelUpdateList);
        
        //List<Agreement_Revision_History__c> revisionChannelUpdateList=[select id,FieldAPI__c,To__c,FieldLabel__c,From__c,Channel_SF_ID__c from Agreement_Revision_History__c where Agreement__c=:agreementIds AND Type__c='Agreement Channel'];
        
        for(AgreementChannel__c agChannels:channelList){
            for(Agreement_Revision_History__c revisionChannelHistory:revisionChannelUpdateList){
                               
                if((revisionChannelHistory.From__c != string.valueof(agChannels.get(revisionChannelHistory.FieldAPI__c)))&& (String.valueof(revisionChannelHistory.FieldAPI__c)==channelMap.get(agChannels.Id)) && (String.valueof(agChannels.Id)==String.valueof(revisionChannelHistory.Channel_SF_ID__c))){
                    
                    revisionChannelHistory.To__c=string.valueof(agChannels.get(revisionChannelHistory.FieldAPI__c));
                    revisionChannelHistory.Type__c='Agreement Channel';
                    revisionChannelHistory.Channel_Action__c='Update';
                    revisionChannelUpdateListFinal.add(revisionChannelHistory);

                }                  
            }

        }
        system.debug('revisionChannelUpdateListFinal:::'+revisionChannelUpdateListFinal.size());
        update revisionChannelUpdateListFinal;
        
    }

    @TestVisible
    public static void deletedChannelRevisions(Set<Id> aggIds, Set<Id> channelId){
    List<Agreement_Revision_History__c> revisionChannelDelListFinal=new List<Agreement_Revision_History__c>();   
    List<Agreement_Revision_History__c> revisionChannelDelList= new PNR_AgreementRevHistorySelector().selectByAgrmntChnl(aggIds,channelId);
        system.debug('%%%revisionChannelDelListNEW - Update method%%%'+revisionChannelDelList);
 
    //List<Agreement_Revision_History__c> revisionChannelDelList=[select id,FieldAPI__c,To__c,FieldLabel__c,From__c,Channel_SF_ID__c from Agreement_Revision_History__c where Agreement__c=:aggIds AND Type__c='Agreement Channel' AND Channel_SF_ID__c=:channelId];
        for(Agreement_Revision_History__c deletedRevChannels:revisionChannelDelList){
            deletedRevChannels.Channel_Action__c='Delete';
            revisionChannelDelListFinal.add(deletedRevChannels);
        }

        system.debug('DELETED CHANNELS%%%'+revisionChannelDelListFinal.size());
        update revisionChannelDelListFinal;
    }

    public static void updateAgreementRevisions(List<Apttus__APTS_Agreement__c> agList) {   
         
        Set<Id> revSet=new Set<Id> ();
        for(Apttus__APTS_Agreement__c ag:agList){
            revSet.add(ag.Id);
        }
        List<Agreement_Revision_History__c> revisionUpdateList= new PNR_AgreementRevHistorySelector().selectAgreementRevision(revSet);
        system.debug('%%%revisionChannelUpdateList22NEW - Update method%%%'+revisionUpdateList);
    
        //List<Agreement_Revision_History__c> revisionUpdateList=[select id,FieldAPI__c,To__c,FieldLabel__c,From__c from Agreement_Revision_History__c where Agreement__c=:revSet AND Type__c='Agreement'];
        Schema.FieldSet fieldSetAgreement = Schema.SObjectType.Apttus__APTS_Agreement__c.fieldSets.Agreement_Revisions_History;
        Map<String,String> fsfieldsMap=new Map<String,String>();

        List<Agreement_Revision_History__c> revisionUpdateListFinal=new List<Agreement_Revision_History__c>();
        List<Agreement_Revision_History__c> revisionDeleteListFinal=new List<Agreement_Revision_History__c>();
        for(Schema.FieldSetMember fsMember:fieldSetAgreement.getFields()){
            fsfieldsMap.put(fsMember.getLabel(),fsMember.getFieldPath());
        }
              
        
        for(Apttus__APTS_Agreement__c chngdAgg:agList){
            for(Agreement_Revision_History__c revisionUpdate:revisionUpdateList){            
                if(revisionUpdate.From__c != string.valueof(chngdAgg.get(revisionUpdate.FieldAPI__c))){                                    
                   revisionUpdate.To__c=string.valueof(chngdAgg.get(revisionUpdate.FieldAPI__c));
                   revisionUpdateListFinal.add(revisionUpdate);                 
                }
                else{
                    revisionDeleteListFinal.add(revisionUpdate);                    
                }
            }
        }
       
        system.debug('revisionUpdateList:::'+revisionUpdateListFinal.size());
        system.debug('revisionDeleteListFinal::'+revisionDeleteListFinal.size());
        if(revisionUpdateListFinal.size()<=10000){
            update revisionUpdateListFinal;
        }
        if(revisionDeleteListFinal.size()<=10000){
         delete revisionDeleteListFinal;
       }
    }
    
    
   public static List<Apttus__APTS_Agreement__c> getAgreementList(Id oppId) {
        List<Apttus__APTS_Agreement__c> agreementList=[select id,Apttus__Contract_Start_Date__c,Apttus__Contract_End_Date__c,Apttus_Approval__Approval_Status__c, Apttus__Status__c,Apttus__Term_Months__c,Apttus__Related_Opportunity__c from Apttus__APTS_Agreement__c where Apttus__Related_Opportunity__c=:oppId ORDER BY CreatedDate DESC LIMIT 1];
        system.debug('agreementList: ' + agreementList.size());      
        return agreementList;
    }
    
    public static List<Agreement_Revision_History__c> getAgreements(Id agreement) {
        List<Agreement_Revision_History__c> agreementList=[select id,Name,CreatedDate, From__c,To__c,FieldAPI__c,FieldLabel__c,Channel_Action__c,Type__c from Agreement_Revision_History__c where Agreement__c=:agreement and (Type__c = 'Agreement Channel' OR Type__c = 'Agreement') ORDER BY CreatedDate DESC];
        system.debug('agreementList: ' + agreementList.size());      
        return agreementList;
    }
}