clmpkg/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

clmpkg/classes/PNR_Agreements.cls
public with sharing class PNR_Agreements extends PNR_SObjectDomain {
    @TestVisible
    private static Boolean triggerDisabled = false;
    public integer count2=0;
    public integer count=0;
    public PNR_Agreements(List<Apttus__APTS_Agreement__c> sObjectList) {
        super(sObjectList);
    }
    
  
    public override void onApplyDefaults() {
        for(Apttus__APTS_Agreement__c agr :(List<Apttus__APTS_Agreement__c>)getRecords()){
            if (agr.Apttus__Status__c == 'In Amendment') {
                agr.Apttus_Approval__Approval_Status__c = 'Not Submitted';
            }
        }
    }

    public override void onAfterInsert() {

        Savepoint sp = Database.setSavePoint();
        
        try {                      
           createAgreementRevisions(null);         
        } catch (Exception e) {
            System.debug(LoggingLevel.Error, e);
            System.debug(LoggingLevel.Error, e.getLineNumber());
                       
            Database.rollback(sp);
        }
    }
    
  
    public override void onAfterUpdate(Map<Id, SObject> existingRecords) {
        
        Savepoint sp = Database.setSavePoint();
        
        try {
             updateAgreementRevisions(existingRecords);          
         
        } catch (Exception e) {
            System.debug(LoggingLevel.Error, e.getLineNumber());           
            System.debug(LoggingLevel.Error, e.getMessage());
            Database.rollback(sp);
        }
    }


    @TestVisible
    private void createAgreementRevisions(Map<Id, SObject> existingRecords) { 
        List<Apttus__APTS_Agreement__c> agreementFromValues=new List<Apttus__APTS_Agreement__c>();
       
            
        for(Apttus__APTS_Agreement__c agrmnt:(List<Apttus__APTS_Agreement__c>)getRecords()){         
            if(agrmnt.Apttus__Status__c=='In Amendment' && agrmnt.Apttus__Status_Category__c=='Request'){            
               agreementFromValues.add(agrmnt);
             
            }                      
        }
         System.debug('agreementFromValues::'+agreementFromValues);
        if(!agreementFromValues.IsEmpty()){
            PNR_AgreementService.createAgreementRevisions(agreementFromValues);
        }
    }

    @TestVisible
    private void updateAgreementRevisions(Map<Id, SObject> existingRecords) { 
        Map<Id, Apttus__APTS_Agreement__c> existingAgreements = (Map<Id, Apttus__APTS_Agreement__c>)existingRecords;
        List<Apttus__APTS_Agreement__c> agreementToValues=new List<Apttus__APTS_Agreement__c>();
        Apttus__APTS_Agreement__c oldAgr;
        Map<String,Apttus__APTS_Agreement__c> changedAggs=new Map<String,Apttus__APTS_Agreement__c>();

        
        //Field sets
        Schema.FieldSet fieldSetAgreement = Schema.SObjectType.Apttus__APTS_Agreement__c.fieldSets.Agreement_Revisions_History;
       
        for(Apttus__APTS_Agreement__c agrmnt:(List<Apttus__APTS_Agreement__c>)getRecords()){
            
            if(existingAgreements.containsKey(agrmnt.Id)){               
                oldAgr =existingAgreements.get(agrmnt.Id);
            }

            
            for( Schema.FieldSetMember fsMember:fieldSetAgreement.getFields()){
                if( oldAgr != null  &&
                ((
                    String.valueof(oldAgr.get(fsMember.getFieldPath())) != String.valueof(agrmnt.get(fsMember.getFieldPath()))                  
                ) &&
                (   agrmnt.Apttus__Status__c=='Submitted Request' && agrmnt.Apttus__Status_Category__c=='Request'))
                )
                         
                {
                    agreementToValues.add(agrmnt);
                    break;
                }
      
            }
            if(agreementToValues.isEmpty() && agrmnt.Apttus__Status__c=='Submitted Request' && agrmnt.Apttus__Status_Category__c=='Request' ){                  
                    agreementToValues.add(agrmnt);
            }
            system.debug('agreementToValues%%'+agreementToValues);
          //  PNR_AgreementService.updateAgreementRevisions(agreementToValues);
        }
        
        if(!agreementToValues.isEmpty()){
             PNR_AgreementService.updateAgreementRevisions(agreementToValues);
        }
    }
   

    public class Constructor implements PNR_SObjectDomain.IConstructable {

        public PNR_SObjectDomain construct(List<SObject> sObjectList) {
            return new PNR_Agreements(sObjectList);
        }
    }
}