clmpkg/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_Start_Date__c</fullName>
        <description>The effective date of the agreement</description>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N50000001Xl0FEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Version_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Version Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

clmpkg/objects/OpportunityStagesLookup__mdt.object
<CustomObject>
    <description>This drives the opportunity stage names based on Approval Status, Status Category on Apttus Agreements</description>
    <fields>
        <fullName>Agreement_Status__c</fullName>
        <label>Agreement Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity_Stage__c</fullName>
        <label>Opportunity Stage</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StatusCheckRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>StatusCheckRequired</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status_Category__c</fullName>
        <label>Status Category</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>OpportunityStagesLookup</label>
    <pluralLabel>OpportunityStagesLookups</pluralLabel>
</CustomObject>

clmpkg/classes/Twitch_AgreementTriggerHandler.cls
//
// (c) 2018 Appirio, Inc.
//
// Apex Class Name : Twitch_AgreementTriggerHandler.cls
// For Apex Trigger: Twitch_AgreementTrigger.trigger
// For sObject: Apttus__APTS_Agreement__c
// Description: This apex class is a handler class for  Twitch_AgreementTrigger.trigger
//
// 15th Mar 2018  Abhimanyu Tanwar   Original (Task # T-XXXXX) - Please see the task description for more details.
//
public class Twitch_AgreementTriggerHandler {
  
  private Id agreementTwitchCLRecType = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get(Label.AGREEMENT_REC_TYPE_TWITCH_CL).getRecordTypeId();
  private Id oppISCARecType = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(Label.OPP_IS_CA_REC_TYPE).getRecordTypeId(); 

  //Method called before Insert
  public void beforeInsert(List<Apttus__APTS_Agreement__c> newList) {
      updateAccountNameFromOpportunity(newList);
      updateAgreementName(newList);
  }
  
  //Method called After Insert
  public void afterInsert(List<Apttus__APTS_Agreement__c> newList) {
      validateActiveAgreement(newList);
  }

  //Method called Before Update
  public void beforeUpdate(List<Apttus__APTS_Agreement__c> newList, Map<Id,Apttus__APTS_Agreement__c> oldMap) {
      validateActiveAgreement(newList);
      updateAgreementName(newList);
  }
  
  //Method called After Update
  public void afterUpdate(List<Apttus__APTS_Agreement__c> newList, Map<Id,Apttus__APTS_Agreement__c> oldMap) {
    //  updateOpporunityStage(newList,oldMap);
  }

  private void validateActiveAgreement(List<Apttus__APTS_Agreement__c> newList){
    
    Map<Id,List<Apttus__APTS_Agreement__c>> oppIdToAgreementMap = new Map<Id,List<Apttus__APTS_Agreement__c>>();
    Set<Id> agreementIds = new Set<Id>();
    
    for(Apttus__APTS_Agreement__c agreement : newList) {
      if( agreement.RecordTypeId == agreementTwitchCLRecType && 
          agreement.Apttus__Related_Opportunity__c != null && 
          agreement.Apttus__Status_Category__c == Label.AGREEMENT_CATEGORY_IN_EFFECT && 
          agreement.Apttus__Status__c == Label.AGREEMENT_STATUS_ACTIVATED ) {
        oppIdToAgreementMap.put(agreement.Apttus__Related_Opportunity__c,new List<Apttus__APTS_Agreement__c>() );
        agreementIds.add(agreement.Id);
      }
    }
    
    for(Apttus__APTS_Agreement__c agreement : [ SELECT Id,Apttus__Related_Opportunity__c
                                                FROM Apttus__APTS_Agreement__c 
                                                WHERE Apttus__Related_Opportunity__c IN : oppIdToAgreementMap.keySet()
                                                AND Apttus__Related_Opportunity__r.RecordTypeId =: oppISCARecType
                                                AND Apttus__Status_Category__c =: Label.AGREEMENT_CATEGORY_IN_EFFECT 
                                                AND Apttus__Status__c =: Label.AGREEMENT_STATUS_ACTIVATED])
    {
      if(!oppIdToAgreementMap.containsKey(agreement.Apttus__Related_Opportunity__c)) {
        oppIdToAgreementMap.put(agreement.Apttus__Related_Opportunity__c,new List<Apttus__APTS_Agreement__c>());
      }
      oppIdToAgreementMap.get(agreement.Apttus__Related_Opportunity__c).add(agreement);
    }
    
    for(Apttus__APTS_Agreement__c agreement : newList) {
      if( agreementIds.contains(agreement.Id) && 
          oppIdToAgreementMap.containsKey(agreement.Apttus__Related_Opportunity__c) && 
          oppIdToAgreementMap.get(agreement.Apttus__Related_Opportunity__c) != null && 
          oppIdToAgreementMap.get(agreement.Apttus__Related_Opportunity__c).size() > 0 ) {
            
        //Check if we are not comparing same records
        for(Apttus__APTS_Agreement__c agreementOppChild : oppIdToAgreementMap.get(agreement.Apttus__Related_Opportunity__c)) {
          if(agreementOppChild.Id != agreement.Id ) {
            agreement.addError(Label.ONE_ACTIVE_AGREEMENT_ERROR); 
          }
        }
      }
    }
  }
  
 /* private void updateOpporunityStage(List<Apttus__APTS_Agreement__c> newList, Map<Id,Apttus__APTS_Agreement__c> oldMap) {
    
    Map<Id,Opportunity> oppIdToOppMap = new Map<Id,Opportunity>();
 
    for(Apttus__APTS_Agreement__c agreement : newList){
      if( agreement.RecordTypeId == agreementTwitchCLRecType && 
          agreement.Apttus__Related_Opportunity__c != null && 
          agreement.Apttus__Status_Category__c == Label.AGREEMENT_CATEGORY_IN_EFFECT && 
          agreement.Apttus__Status__c == Label.AGREEMENT_STATUS_ACTIVATED ) {
        oppIdToOppMap.put(agreement.Apttus__Related_Opportunity__c,null);
      }
    }
    
    for(Opportunity opp : [ SELECT Id,Name FROM Opportunity WHERE Id IN : oppIdToOppMap.keySet()])
    {
      opp.StageName = Label.OPP_STAGE_SIGNED;
      oppIdToOppMap.put(opp.Id,opp);
    }
    
    if(!oppIdToOppMap.values().isEmpty()) {
      update oppIdToOppMap.values();
    }
  }*/
  
  private void updateAgreementName(List<Apttus__APTS_Agreement__c> newList) {

    Map<Id,String> accountIdToNameMap = new Map<Id,String>();
 
    for(Apttus__APTS_Agreement__c agreement : newList){
      if(agreement.RecordTypeId == agreementTwitchCLRecType && agreement.Apttus__Account__c != null ) {
        accountIdToNameMap.put(agreement.Apttus__Account__c,null);
      }
    }
    
    for(Account acc : [ SELECT Id,Name FROM Account WHERE Id IN : accountIdToNameMap.keySet()])
    {
      accountIdToNameMap.put(acc.Id,acc.Name);
    }

    for(Apttus__APTS_Agreement__c agreement : newList) {
      if( agreement.RecordTypeId == agreementTwitchCLRecType && 
          agreement.Apttus__Version_Number__c == 0 &&
          agreement.Apttus__Account__c != null &&  
          accountIdToNameMap.containsKey(agreement.Apttus__Account__c) &&
          accountIdToNameMap.get(agreement.Apttus__Account__c) != null ) {
            
          if(agreement.Apttus__Contract_Start_Date__c != null) {
            agreement.Name =  accountIdToNameMap.get(agreement.Apttus__Account__c)+'__Content License__'+
                              agreement.Apttus__Contract_Start_Date__c.month()+'/'+
                              agreement.Apttus__Contract_Start_Date__c.day()+'/'+
                              agreement.Apttus__Contract_Start_Date__c.year();
          }
          else {
            agreement.Name = accountIdToNameMap.get(agreement.Apttus__Account__c)+'__Content License';
          }
      }
    }
  }

  private void updateAccountNameFromOpportunity(List<Apttus__APTS_Agreement__c> newList) {

    Map<Id,Id> opportunityIdToAccIdMap = new Map<Id,Id>();
 
    for(Apttus__APTS_Agreement__c agreement : newList){
      if(agreement.Apttus__Version_Number__c == 0 && agreement.Apttus__Account__c == null ) {
        opportunityIdToAccIdMap.put(agreement.Apttus__Related_Opportunity__c,null);
      }
    }
    
    for(Opportunity opp : [ SELECT Id,AccountId FROM Opportunity 
                                                WHERE Id IN : opportunityIdToAccIdMap.keySet()]
    ){
      opportunityIdToAccIdMap.put(opp.Id,opp.AccountId);
    }

    for(Apttus__APTS_Agreement__c agreement : newList){
      if( agreement.Apttus__Version_Number__c == 0 && 
          agreement.Apttus__Account__c == null &&  
          opportunityIdToAccIdMap.containsKey(agreement.Apttus__Related_Opportunity__c) &&
          opportunityIdToAccIdMap.get(agreement.Apttus__Related_Opportunity__c) != null ) {
            agreement.Apttus__Account__c = opportunityIdToAccIdMap.get(agreement.Apttus__Related_Opportunity__c);
      }
    }
  }
  
  /*
  * Opportunity Stage Advancement Logic
  *
  */
  public void updateOpportunityStatuses(List<Id> relatedOpportunities,List<Apttus__APTS_Agreement__c> agreements){
      Id agreementTwitchCLTecType = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get(Label.AGREEMENT_REC_TYPE_TWITCH_CL).getRecordTypeId(); 
      List<Opportunity> updatedOpportunities=new List<Opportunity>();
      List<OpportunityStagesLookup__mdt> opportunitylookup =new List<OpportunityStagesLookup__mdt>([Select Agreement_Status__c, Approval_Status__c, StatusCheckRequired__c, Opportunity_Stage__c, Status_Category__c from OpportunityStagesLookup__mdt]);
      Map<Id,Opportunity> relatedOpptys=new Map<Id,Opportunity>([Select Id,Name,stageName from Opportunity where Id IN: relatedOpportunities]); 
        for(Apttus__APTS_Agreement__c agreement:agreements){
            if(agreement.RecordTypeId==agreementTwitchCLTecType && agreement.Apttus__Related_Opportunity__c!=null){
                for(OpportunityStagesLookup__mdt opp:opportunitylookup)   {  
                  if(agreement.Apttus_Approval__Approval_Status__c==opp.Approval_Status__c && agreement.Apttus__Status_Category__c == opp.Status_Category__c) {     
                        if(opp.StatusCheckRequired__c){
                            if(agreement.Apttus__Status__c==opp.Agreement_Status__c){
                                //Update only if Oppty Stage is not the same value we want to update
                                if(relatedOpptys.get(agreement.Apttus__Related_Opportunity__c).StageName!=opp.Opportunity_Stage__c){
                                    system.debug('entered 1st IF:'+relatedOpptys.get(agreement.Apttus__Related_Opportunity__c).StageName +' , '+opp.Opportunity_Stage__c);
                                     relatedOpptys.get(agreement.Apttus__Related_Opportunity__c).StageName=opp.Opportunity_Stage__c;
                                     updatedOpportunities.add(relatedOpptys.get(agreement.Apttus__Related_Opportunity__c));
                                }
                               
                            } 
                        }
                        else
                        {
                        //Update only if Oppty Stage is not the same value we want to update
                         if(relatedOpptys.get(agreement.Apttus__Related_Opportunity__c).StageName!=opp.Opportunity_Stage__c){                       
                            system.debug('entered 2nd IF:'+relatedOpptys.get(agreement.Apttus__Related_Opportunity__c).StageName +','+opp.Opportunity_Stage__c);
                             relatedOpptys.get(agreement.Apttus__Related_Opportunity__c).StageName=opp.Opportunity_Stage__c;
                             updatedOpportunities.add(relatedOpptys.get(agreement.Apttus__Related_Opportunity__c));
                            }
                        }
                        
                        system.debug('test-updateoppstatus' +agreement.Apttus_Approval__Approval_Status__c +'&&'+opp.Approval_Status__c);        
                        system.debug('updatedOpportunitiess'+updatedOpportunities);
                   }  
               } 


            }

        }
        if(!updatedOpportunities.IsEmpty()){
            update updatedOpportunities;
       }
  }
}