clmpkg/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_Start_Date__c</fullName>
        <description>The effective date of the agreement</description>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N50000001Xl0FEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Version_Number__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Version Number</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

clmpkg/classes/Twitch_AgreementTriggerHandler_Test.cls
//
// (c) 2018 Appirio, Inc.
//
// Test Class Name: Twitch_AgreementTriggerHandler_Test.cls
// For Apex Class: Twitch_AgreementTriggerHandler.cls
// Description: This apex class is Test class for Twitch_AgreementTriggerHandler.cls
//
// 15th Mar 2018  Abhimanyu Tanwar   Original (Task # T-XXXXX) - Please see the task description for more details.
//
@isTest
private class Twitch_AgreementTriggerHandler_Test {
  
  //Test setup method
  @testSetup static void setup() {
    
    Id oppISCARecType = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(Label.OPP_IS_CA_REC_TYPE).getRecordTypeId(); 
    List<Account> listAccounts = Twitch_TestUtils.createAccountRecords('Test Account', 1, true);
    
    List<Opportunity> opportunities = Twitch_TestUtils.createOpportunityRecords('Test Opportunity',
                                    'New-Single', System.Today(), listAccounts.get(0).Id, 200, false);
                                    
    for(Opportunity opp: opportunities) {
        opp.BroadcastStartDate__c = System.today();
    }
    insert opportunities;   
    
    List<OpportunityChannel__c> channelList = new List<OpportunityChannel__c>();
    for(Opportunity opp: opportunities) {
        opp.RecordTypeId = oppISCARecType;
        OpportunityChannel__c channel = new OpportunityChannel__c();
        channel.Opportunity__c = opp.Id;
        channel.Streamer__c = listAccounts.get(0).Id;
        channel.TwitchUserIDManualEntry__c = 'x123345';
        channel.TwitchUsernameManualEntry__c = 'x123345';
        channelList.add(channel);
    }
    insert channelList;
    
    Id agreementTwitchCLTecType = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get(Label.AGREEMENT_REC_TYPE_TWITCH_CL).getRecordTypeId(); 
    List<Apttus__APTS_Agreement__c> agreements = Twitch_TestUtils.createAgreementRecords('Agreement #',null, 200,false);
    
    for(integer i = 0; i< 200; i++) {
      agreements.get(i).Apttus__Related_Opportunity__c = opportunities.get(i).Id;
      agreements.get(i).RecordTypeId = agreementTwitchCLTecType;
      agreements.get(i).Apttus__Contract_Start_Date__c = System.today();
      agreements.get(i).Apttus__Version_Number__c = 1;
    }
    
    insert agreements;
    
    for(integer i = 0; i< 200; i++) {
      agreements.get(i).Apttus__Status_Category__c = Label.AGREEMENT_CATEGORY_IN_EFFECT ;
      agreements.get(i).Apttus__Status__c = Label.AGREEMENT_STATUS_ACTIVATED;
      agreements.get(i).Apttus__Contract_End_Date__c = System.today();
      agreements.get(i).Apttus_Approval__Approval_Status__c = 'Approved';
    }
    update agreements;
  }
  
  // Test Method
  @isTest static void testMethod1() {
    Id agreementTwitchCLRecType = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get(Label.AGREEMENT_REC_TYPE_TWITCH_CL).getRecordTypeId(); 
    Id oppISCARecType = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(Label.OPP_IS_CA_REC_TYPE).getRecordTypeId(); 
    
    System.assertEquals(200,[SELECT Id FROM Opportunity WHERE StageName =:Label.OPP_STAGE_SIGNED ].size());
    
    List<Account> listAccounts = Twitch_TestUtils.createAccountRecords('Test Account', 1, true);
  
    List<Opportunity> opportunities = Twitch_TestUtils.createOpportunityRecords('Test Opportunity', 
                                      'New-Single', System.Today(), listAccounts.get(0).Id, 200, false);
                                    
    for(Opportunity opp: opportunities) {
        opp.BroadcastStartDate__c = System.today();
    }
    insert opportunities;

    List<Apttus__APTS_Agreement__c> agreements = Twitch_TestUtils.createAgreementRecords('Agreement2 #',null, 200,false);
    
    for(integer i = 0; i< 200; i++) {
      agreements.get(i).Apttus__Status_Category__c = Label.AGREEMENT_CATEGORY_IN_EFFECT;
      agreements.get(i).Apttus__Status__c = Label.AGREEMENT_STATUS_ACTIVATED;
      agreements.get(i).Apttus__Contract_End_Date__c = System.today();
      agreements.get(i).Apttus_Approval__Approval_Status__c = 'Approved';
      agreements.get(i).Apttus__Related_Opportunity__c = opportunities.get(i).Id;
      agreements.get(i).RecordTypeId = agreementTwitchCLRecType;
      agreements.get(i).Apttus__Contract_Start_Date__c = System.today();
    }
    
    try{
      insert agreements;
    }
    catch(Exception e) {
      System.assertEquals(true,e.getMessage().contains(Label.ONE_ACTIVE_AGREEMENT_ERROR));
    }
  }
}