clmpkg/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>AdDensityRequirementMinHr__c</fullName>
        <defaultValue>6</defaultValue>
        <description>Field shows Partners neg. # ads displayed and # of advertistments displayed per hour needed in the agreement.</description>
        <label>Ad Density Requirement (# Min / Hr)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Apttus_Approval__Approval_Status__c</fullName>
        <label>Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Approval Required</fullName>
                </value>
                <value>
                    <fullName>Not Submitted</fullName>
                    <default>true</default>
                    <label>Not Submitted</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The link to the account record to identify the external party to this agreement</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>R00N50000001Xl0UEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_End_Date__c</fullName>
        <description>The end date for this agreement</description>
        <label>Agreement End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Contract_Start_Date__c</fullName>
        <description>The effective date of the agreement</description>
        <label>Agreement Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Apttus__Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N50000001Xl0FEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Term_Months__c</fullName>
        <description>Indicates the duration in months of the contract from the start date</description>
        <label>Term (Months)</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CustomAdDensityRequirement__c</fullName>
        <label>Custom Ad Density Requirement</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VODExclusivity__c</fullName>
        <description>Field is used in calculations to support the deal/partner model process.</description>
        <label>VOD Exclusivity</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>12 Hours</fullName>
                </value>
                <value>
                    <fullName>24 Hours</fullName>
                </value>
                <value>
                    <fullName>7 Days</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

clmpkg/classes/PNR_AgreementSelector.cls
public with sharing class PNR_AgreementSelector extends PNR_SObjectSelector {

    public PNR_AgreementSelector() {
        this(false);
    }
   
    public PNR_AgreementSelector(Boolean includeFieldSetFields) {
        this(includeFieldSetFields, true, false);
    }
    
    public PNR_AgreementSelector(Boolean includeFieldSetFields, Boolean enforceCRUD, Boolean enforceFLS) {
        super(includeFieldSetFields, enforceCRUD, enforceFLS);
    }
   
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
                Apttus__APTS_Agreement__c.Id,
                Apttus__APTS_Agreement__c.Name,
                Apttus__APTS_Agreement__c.Apttus__Related_Opportunity__c,
                Apttus__APTS_Agreement__c.Apttus__Contract_Start_Date__c,
                Apttus__APTS_Agreement__c.Apttus__Contract_End_Date__c,
                Apttus__APTS_Agreement__c.Apttus__Status__c,
                Apttus__APTS_Agreement__c.Apttus__Term_Months__c,
                Apttus__APTS_Agreement__c.Apttus_Approval__Approval_Status__c,
                Apttus__APTS_Agreement__c.Apttus__Status_Category__c,
                Apttus__APTS_Agreement__c.Apttus__Account__c,
                Apttus__APTS_Agreement__c.AdDensityRequirementMinHr__c,
                Apttus__APTS_Agreement__c.VODExclusivity__c,
                Apttus__APTS_Agreement__c.CustomAdDensityRequirement__c

        };
    }


    public Schema.SObjectType getSObjectType() {
        return Apttus__APTS_Agreement__c.sObjectType;
    }

  
    public override String getOrderBy() {
        return 'CreatedDate';
    }
    
    public override String getLimitClause(){
        return 'DESC LIMIT 1';
    }
    public List<Apttus__APTS_Agreement__c> selectByOpportunityId(Set<Id> opptyIdSet) {
        assertIsAccessible();

        String query = String.format(
                ' SELECT {0}' +
                        ' FROM {1}' +
                        ' WHERE Apttus__Related_Opportunity__c =: opptyIdSet' +
                        ' ORDER BY {2}' +
                        ' {3}',
                new List<String> {
                        getFieldListString(),
                        getSObjectName(),
                        getOrderBy(),
                        getLimitClause()
                }
        );
        
        return Database.query(query);
    }
    public String selectByAggId(String relationshipFieldPath) {
        assertIsAccessible();

        String query='';
        
            String strTest = getFieldListString();
            String[] arrTest = strTest.split(',');

            for(String s:arrTest){
                query+= relationshipFieldPath+'.'+s+',';
            }
           query=query.removeEnd(',');
         
        system.debug('Agreement Selector -query'+query);
        return query;
    }
}