clmpkg/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>SignatoryName__c</fullName>
        <description>Field is used in the DocuSign auto-add set-up. Do not show this field in the page layout.</description>
        <label>Signatory Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Signatory__c</fullName>
        <inlineHelpText>Please enter the email address of the team/user signatory.</inlineHelpText>
        <label>Signatory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TwitchSignatoryName__c</fullName>
        <description>Field is used in the DocuSign auto-add set-up.  Do not show this field in the page layout.</description>
        <label>Twitch Signatory Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Twitch_Signatory__c</fullName>
        <inlineHelpText>Please enter the email address of the Twitch signatory.</inlineHelpText>
        <label>Twitch Signatory</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

clmpkg/classes/PNR_AgreementActionsCtrlTest.cls
@isTest
private class PNR_AgreementActionsCtrlTest {
    static testMethod void testgetCreateEnvelopeURL(){
        Apttus__APTS_Agreement__c testAgr = new Apttus__APTS_Agreement__c();
        testAgr.Signatory__c = 'testsigner@gmail.com';
        testAgr.SignatoryName__c = 'Test Signatory';
        testAgr.Twitch_Signatory__c = 'testtwitchsigner@twitch.tv';
        testAgr.TwitchSignatoryName__c = 'Test Twitch Signer';
        String res = PNR_AgreementActionsCtrl.getCreateEnvelopeURL(testAgr);
        System.assert(res.containsIgnoreCase('dsfs__DocuSign_CreateEnvelope'));
    }
}