clmpkg/objects/Apttus__APTS_Agreement__c.object
<CustomObject>
    <description>Represents an agreement in the system</description>
    <fields>
        <fullName>Apttus__Related_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>R00N50000001Xl0FEAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Apttus__Status_Category__c</fullName>
        <description>The higher level state of the agreement – In Authoring, In Effect, Expired, etc.  These are Apttus reserved values and cannot be changed.</description>
        <label>Status Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                    <default>true</default>
                    <label>Request</label>
                </value>
                <value>
                    <fullName>In Authoring</fullName>
                </value>
                <value>
                    <fullName>In Signatures</fullName>
                </value>
                <value>
                    <fullName>In Filing</fullName>
                </value>
                <value>
                    <fullName>In Effect</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Amended</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apttus__Status__c</fullName>
        <description>The sub stage of an agreement – the status underneath a given status category.  These are generally modifiable by the customer except for the following values which are Apttus reserved to manage agreement lifecycles:

Request, Submitted Request,
Cancelled Request, In Amendment, Being Amended, Superseded, Activated, Expired, Internal Signatures, Author Contract, Expired, Terminated,  Ready for Signatures, Fully Signed, Signature Declined</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Apttus__Status_Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Request</fullName>
                </value>
                <value>
                    <fullName>Request Approval</fullName>
                </value>
                <value>
                    <fullName>Submitted Request</fullName>
                </value>
                <value>
                    <fullName>Approved Request</fullName>
                </value>
                <value>
                    <fullName>Cancelled Request</fullName>
                </value>
                <value>
                    <fullName>In Amendment</fullName>
                </value>
                <value>
                    <fullName>Author Contract</fullName>
                </value>
                <value>
                    <fullName>Language Approval</fullName>
                </value>
                <value>
                    <fullName>Language Approved</fullName>
                </value>
                <value>
                    <fullName>Internal Signatures</fullName>
                </value>
                <value>
                    <fullName>Other Party Signatures</fullName>
                </value>
                <value>
                    <fullName>Activated</fullName>
                </value>
                <value>
                    <fullName>Being Amended</fullName>
                </value>
                <value>
                    <fullName>Being Renewed</fullName>
                </value>
                <value>
                    <fullName>In Renewal</fullName>
                </value>
                <value>
                    <fullName>Superseded</fullName>
                </value>
                <value>
                    <fullName>Being Terminated</fullName>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>In Reconciliation</fullName>
                </value>
                <value>
                    <fullName>Reconciled</fullName>
                </value>
                <value>
                    <fullName>Internal Review</fullName>
                </value>
                <value>
                    <fullName>Other Party Review</fullName>
                </value>
                <value>
                    <fullName>Signature Declined</fullName>
                </value>
                <value>
                    <fullName>Ready for Signatures</fullName>
                </value>
                <value>
                    <fullName>Fully Signed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Agreement</label>
    <nameField>
        <label>Agreement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Agreements</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

clmpkg/classes/Twitch_RelatedAgreementTriggerHandler.cls
//
// (c) 2018 Appirio, Inc.
//
// Apex Class Name : Twitch_RelatedAgreementTriggerHandler.cls
// For Apex Trigger: Twitch_RelatedAgreementTrigger.trigger
// For sObject: Apttus__APTS_Agreement__c
// Description: This apex class is a handler class for  Twitch_RelatedAgreementTrigger.trigger
//
// 27th Apr 2018  Abhimanyu Tanwar   Original (Task # T-XXXXX) - Please see the task description for more details.
//
public class Twitch_RelatedAgreementTriggerHandler  {
  
  private Id agreementTwitchCLRecType = Schema.SObjectType.Apttus__APTS_Agreement__c.getRecordTypeInfosByName().get(Label.AGREEMENT_REC_TYPE_TWITCH_CL).getRecordTypeId();
  private Id oppISCARecType = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(Label.OPP_IS_CA_REC_TYPE).getRecordTypeId(); 
  
  //Method called After Insert
  public void afterInsert(List<Apttus__APTS_Related_Agreement__c> newList) {
      updateRelatedAgreementStages(newList);
  }
  
  private void updateRelatedAgreementStages(List<Apttus__APTS_Related_Agreement__c> newList) {
    
    Set<Id> relationToSupersued = new Set<Id>();
    Map<Id,List<Id>> AgreementIDAmendFromAgreementMap = new Map<Id,List<Id>>();
    Map<Id,List<Id>> AgreementIDRenewedFromAgreementMap = new Map<Id,List<Id>>();
    
    List<Apttus__APTS_Agreement__c> amendedAgreementList = new List<Apttus__APTS_Agreement__c>();
    List<Apttus__APTS_Agreement__c> renewedAgreementList = new List<Apttus__APTS_Agreement__c>();
    List<Apttus__APTS_Related_Agreement__c> updateRelationList = new List<Apttus__APTS_Related_Agreement__c>();

    for( Apttus__APTS_Related_Agreement__c agreementRelation: [ SELECT  Id,
                                                                        Apttus__Relationship_From_Type__c,
                                                                        Apttus__APTS_Contract_To__c,
                                                                        Apttus__APTS_Contract_From__c
                                                                FROM Apttus__APTS_Related_Agreement__c 
                                                                WHERE ID IN : newList
                                                                AND ( Apttus__Relationship_From_Type__c = 'Is Amended By' OR Apttus__Relationship_From_Type__c = 'Is Renewed By' )
                                                                AND Apttus__APTS_Contract_To__r.Apttus__Related_Opportunity__r.RecordTypeId =: oppISCARecType ]) {
     
      if(agreementRelation.Apttus__Relationship_From_Type__c == 'Is Amended By') {
        Apttus__APTS_Agreement__c agreement = new Apttus__APTS_Agreement__c();
        agreement.Id = agreementRelation.Apttus__APTS_Contract_From__c;
        agreement.Apttus__Status__c = 'Superseded';
        agreement.Apttus__Status_Category__c = 'Amended';
        amendedAgreementList.add(agreement);
        
        
        Apttus__APTS_Related_Agreement__c agreementRel = new Apttus__APTS_Related_Agreement__c();
        agreementRel.Id = agreementRelation.Id;
        agreementRel.Apttus__Relationship_From_Type__c = 'Is Superceded By';
        updateRelationList.add(agreementRel);
      }
      else if(agreementRelation.Apttus__Relationship_From_Type__c == 'Is Renewed By') {
        Apttus__APTS_Agreement__c agreement = new Apttus__APTS_Agreement__c();
        agreement.Id = agreementRelation.Apttus__APTS_Contract_From__c;
        agreement.Apttus__Status__c = 'Superseded';
        agreement.Apttus__Status_Category__c = 'Renewed';
        amendedAgreementList.add(agreement);
        
        
        Apttus__APTS_Related_Agreement__c agreementRel = new Apttus__APTS_Related_Agreement__c();
        agreementRel.Id = agreementRelation.Id;
        agreementRel.Apttus__Relationship_From_Type__c = 'Is Superceded By';
        updateRelationList.add(agreementRel);
      }
    }
    
    if(!amendedAgreementList.isEmpty()) {
      update amendedAgreementList;
      System.debug(amendedAgreementList);
    }
    
    if(!updateRelationList.isEmpty()) {
      update updateRelationList;
      System.debug(updateRelationList);
    }
  }
}